networks:
  ocpi:
    driver: bridge
services:
  evse_manager_scheduler:
    restart: always
    image: evsemanager/evse-manager-scheduler:${EVSE_MANAGER_SCHEDULER_VERSION:-1.0.0}
    environment:
      - EVSE_MANAGER_SCHEDULER_VERSION=${EVSE_MANAGER_SCHEDULER_VERSION}
      - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
      - NODE_ENV=${NODE_ENV}
      - PORT_EVSE_MANAGER_SCHEDULER=${PORT_EVSE_MANAGER_SCHEDULER}
      - PAYMENT_SERVER_URL=${PAYMENT_SERVER_URL}
      - FIREBASE_URL=${FIREBASE_URL}
      - FIREBASE_CREDENTIALS_PATH=${FIREBASE_CREDENTIALS_PATH}
      - FIREBASE_FUNCTIONS_REGION=${FIREBASE_FUNCTIONS_REGION}
      - FIREBASE_API_KEY=${FIREBASE_API_KEY}
      - FIREBASE_AUTH_DOMAIN=${FIREBASE_AUTH_DOMAIN}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_STORAGE_BUCKET=${FIREBASE_STORAGE_BUCKET}
      - FIREBASE_MESSAGING_SENDER_ID=${FIREBASE_MESSAGING_SENDER_ID}
      - FIREBASE_APP_ID=${FIREBASE_APP_ID}
      - FIREBASE_MEASUREMENT_ID=${FIREBASE_MEASUREMENT_ID}
      - MONGODB_URL=${MONGODB_URL}
      - OCPP_URL=${OCPP_URL}
      - OCPP_EMAIL=${OCPP_EMAIL}
      - OCPP_PASSWORD=${OCPP_PASSWORD}
      - OCPP_TENANT=${OCPP_TENANT}
      - OCPP_TOKEN=${OCPP_TOKEN}
      - SESSION_PROCESS_INTERVAL=${SESSION_PROCESS_INTERVAL}
    ports:
      - ${PORT_EVSE_MANAGER_SCHEDULER:-3000}:${PORT_EVSE_MANAGER_SCHEDULER:-3000}
    depends_on:
      - db_evse_manager
    volumes:
      - ${PWD}/evse-manager/firebase-credentials.json:/firebase-credentials.json:ro
    extra_hosts:
      - "ocpp-server:host-gateway"
    networks:
      - ocpi

  payment_server:
    restart: always
    image: evsemanager/payment-server:${PAYMENT_SERVER_VERSION:-1.0.0}
    environment:
      - PAYMENT_SERVER_VERSION=${PAYMENT_SERVER_VERSION}
      - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
      - NODE_ENV=${NODE_ENV}
      - PORT_PAYMENT_SERVER=${PORT_PAYMENT_SERVER}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_URL=${FIREBASE_URL}
      - FIREBASE_CREDENTIALS_PATH=${FIREBASE_CREDENTIALS_PATH}
      - MONGODB_URL=${MONGODB_URL}
      - EVSE_MANAGER_SCHEDULER_URL=${EVSE_MANAGER_SCHEDULER_URL}
      - BLOCKCHAIN_GATEWAY_TEZOS_URL=${BLOCKCHAIN_GATEWAY_TEZOS_URL}
      - BLOCKCHAIN_GATEWAY_EVM_URL=${BLOCKCHAIN_GATEWAY_EVM_URL}
      - PAYMENT_SERVER_NOTIFICATION_INTERVAL=${PAYMENT_SERVER_NOTIFICATION_INTERVAL}
      - PAYMENT_SERVER_RETRY_INTERVAL=${PAYMENT_SERVER_RETRY_INTERVAL}
      - PAYMENT_SERVER_MAX_RETRIES=${PAYMENT_SERVER_MAX_RETRIES}
    ports:
      - ${PORT_PAYMENT_SERVER:-3002}:${PORT_PAYMENT_SERVER:-3002}
    depends_on:
      - db_evse_manager
    volumes:
      - ${PWD}/evse-manager/firebase-credentials.json:/firebase-credentials.json:ro
    extra_hosts:
      - "ocpp-server:host-gateway"
    networks:
      - ocpi

  blockchain_gateway_tezos:
    restart: always
    image: evsemanager/blockchain-gateway-tezos:${BLOCKCHAIN_GATEWAY_TEZOS_VERSION:-1.0.0}
    environment:
      - BLOCKCHAIN_GATEWAY_TEZOS_VERSION=${BLOCKCHAIN_GATEWAY_TEZOS_VERSION}
      - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
      - NODE_ENV=${NODE_ENV}
      - PORT_BLOCKCHAIN_GATEWAY_TEZOS=${PORT_BLOCKCHAIN_GATEWAY_TEZOS}
      - PAYMENT_SERVER_URL=${PAYMENT_SERVER_URL}
      - MONGODB_URL=${MONGODB_URL}
      - TEZOS_ENDPOINT=${TEZOS_ENDPOINT}
      - TEZOS_INTERVAL_PREAPPLY=${TEZOS_INTERVAL_PREAPPLY}
      - TEZOS_INTERVAL_CRAWLER=${TEZOS_INTERVAL_CRAWLER}
      - TEZOS_INTERVAL_INJECTOR=${TEZOS_INTERVAL_INJECTOR}
      - TEZOS_INTERVAL_NOTIFICATION=${TEZOS_INTERVAL_NOTIFICATION}
      - TEZOS_SK_SIGNER=${TEZOS_SK_SIGNER}
      - TEZOS_WRC_CONTRACT=${TEZOS_WRC_CONTRACT}
    ports:
      - ${PORT_BLOCKCHAIN_GATEWAY_TEZOS:-3004}:${PORT_BLOCKCHAIN_GATEWAY_TEZOS:-3004}
    depends_on:
      - db_evse_manager
    extra_hosts:
      - "ocpp-server:host-gateway"
    networks:
      - ocpi

  blockchain_gateway_evm:
    restart: always
    image: evsemanager/blockchain-gateway-evm:${BLOCKCHAIN_GATEWAY_EVM_VERSION:-1.0.0}
    environment:
      - BLOCKCHAIN_GATEWAY_EVM_VERSION=${BLOCKCHAIN_GATEWAY_EVM_VERSION}
      - PORT_BLOCKCHAIN_GATEWAY_EVM=${PORT_BLOCKCHAIN_GATEWAY_EVM}
      - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
      - NODE_ENV=${NODE_ENV}
      - EVM_VIEM_CHAIN=${EVM_VIEM_CHAIN}
      - EVM_WRC_CONTRACT=${EVM_WRC_CONTRACT}
      - EVM_SK_INJECTOR=${EVM_SK_INJECTOR}
      - EVM_TICK=${EVM_TICK}
      - EVM_CONFIRMATION=${EVM_CONFIRMATION}
    ports:
      - ${PORT_BLOCKCHAIN_GATEWAY_EVM:-3006}:${PORT_BLOCKCHAIN_GATEWAY_EVM:-3006}
    depends_on:
      - db_evse_manager
    extra_hosts:
      - "ocpp-server:host-gateway"
    networks:
      - ocpi

  ocpp_listener:
    restart: always
    image: evsemanager/ocpp-listener:${OCPP_LISTENER_VERSION:-1.0.0}
    environment:
      - OCPP_LISTENER_VERSION=${OCPP_LISTENER_VERSION}
      - PORT_OCPP_LISTENER=${PORT_OCPP_LISTENER}
      - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
      - NODE_ENV=${NODE_ENV}
      - EVSE_MANAGER_SCHEDULER_URL=${EVSE_MANAGER_SCHEDULER_URL}
      - OCPP_MONGODB_URL=${OCPP_MONGODB_URL}
      - OCPP_MONGODB_DB=${OCPP_MONGODB_DB}
      - OCPP_MONGODB_TRANSACTIONS=${OCPP_MONGODB_TRANSACTIONS}
      - OCPP_MONGODB_RESUME_TOKENS=${OCPP_MONGODB_RESUME_TOKENS}
      - OCPP_MONGODB_RESUME_TOKEN_ID=${OCPP_MONGODB_RESUME_TOKEN_ID}
      - FIREBASE_OCPP_LISTENER_API_KEY=${FIREBASE_OCPP_LISTENER_API_KEY}
      - FIREBASE_OCPP_LISTENER_AUTH_DOMAIN=${FIREBASE_OCPP_LISTENER_AUTH_DOMAIN}
      - FIREBASE_OCPP_LISTENER_PROJECT_ID=${FIREBASE_OCPP_LISTENER_PROJECT_ID}
      - FIREBASE_OCPP_LISTENER_STORAGE_BUCKET=${FIREBASE_OCPP_LISTENER_STORAGE_BUCKET}
      - FIREBASE_OCPP_LISTENER_MESSAGING_SENDER_ID=${FIREBASE_OCPP_LISTENER_MESSAGING_SENDER_ID}
      - FIREBASE_OCPP_LISTENER_APP_ID=${FIREBASE_OCPP_LISTENER_APP_ID}
      - FIREBASE_OCPP_LISTENER_CLIENT_EMAIL=${FIREBASE_OCPP_LISTENER_CLIENT_EMAIL}
      - FIREBASE_OCPP_LISTENER_CLIENT_PASSWORD=${FIREBASE_OCPP_LISTENER_CLIENT_PASSWORD}
    ports:
      - ${PORT_OCPP_LISTENER:-3008}:${PORT_OCPP_LISTENER:-3008}
    depends_on:
      - db_evse_manager
    extra_hosts:
      - "ocpp-server:host-gateway"
    networks:
      - ocpi

  db_evse_manager:
    image: mongo:4.4.25
    restart: always
    ports:
      - 26037:27017
    command: mongod --noauth
    environment:
      - MONGO_INITDB_DATABASE=charge-sessions
    networks:
      - ocpi